const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const DB_FILE = path.join(__dirname, 'data', 'db.json');
const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || '127.0.0.1';
const readDb = () => JSON.parse(fs.readFileSync(DB_FILE, 'utf8'));
const writeDb = (db) => fs.writeFileSync(DB_FILE, JSON.stringify(db, null, 2));
const id = (p) => `${p}_${crypto.randomBytes(8).toString('hex')}`;
const send = (res, status, payload, headers={}) => { res.writeHead(status, {'content-type':'application/json', ...headers}); res.end(JSON.stringify({success: status < 400, data: status < 400 ? payload : null, error: status >= 400 ? {message: payload.message || payload} : null, requestId: id('req')})); };
const html = (res, body) => { res.writeHead(200, {'content-type':'text/html; charset=utf-8'}); res.end(`<!doctype html><html><head><title>SeasonExam</title><style>body{margin:0;background:#020617;color:#e2e8f0;font-family:system-ui}.wrap{max-width:1100px;margin:auto;padding:28px}.card{border:1px solid #1e293b;background:#0f172a;border-radius:20px;padding:24px;margin:16px 0}.btn{display:inline-block;background:#22d3ee;color:#00111a;padding:10px 16px;border-radius:12px;font-weight:700;text-decoration:none}a{color:#67e8f9}code{background:#111827;padding:2px 6px;border-radius:6px}input,select,textarea{padding:10px;border-radius:10px;border:1px solid #334155;background:#020617;color:white;width:100%;box-sizing:border-box;margin:6px 0}button{padding:10px 16px;border:0;border-radius:10px;background:#22d3ee;font-weight:700}</style></head><body><div class=wrap><nav><b>SeasonExam</b> · <a href=/>Home</a> · <a href=/seasons>Seasons</a> · <a href=/admin>Admin</a></nav>${body}</div></body></html>`); };
const parseBody = (req) => new Promise((resolve) => { let b=''; req.on('data', c => b+=c); req.on('end', () => { try{ resolve(b ? JSON.parse(b) : {}); }catch{ resolve({}); } }); });
const cookieSession = (req) => (req.headers.cookie || '').split('; ').find(x=>x.startsWith('session='))?.split('=')[1];
const userFromReq = (req, db) => db.users.find(u => u.id === db.sessions[cookieSession(req)]);
const requireUser = (req, res, db) => { const u = userFromReq(req, db); if(!u || !u.active){ send(res,401,'Please login'); return null; } return u; };
const requireAdmin = (req,res,db) => { const u=requireUser(req,res,db); if(!u) return null; if(u.role!=='ADMIN'){ send(res,403,'Forbidden'); return null; } return u; };
const validateSeason = (db, seasonId) => { const season=db.seasons.find(s=>s.id===seasonId); const qs=db.questions.filter(q=>q.seasonId===seasonId); const errors=[]; if(!season) errors.push('Season not found'); if(season && !season.name) errors.push('Name is required'); if(!qs.length) errors.push('At least one question is required'); qs.forEach((q,i)=>{ if(!q.text?.trim()) errors.push(`Question ${i+1}: missing text`); if(!q.options || q.options.length < 2) errors.push(`Question ${i+1}: minimum 2 options required`); if(q.options.filter(o=>o.isCorrect).length !== 1) errors.push(`Question ${i+1}: exactly one correct option required`); if(q.options.some(o=>!o.text?.trim())) errors.push(`Question ${i+1}: empty option`); }); return errors; };
const publicAttempt = (a) => ({...a, attemptQuestions:a.attemptQuestions.map(q=>({id:q.id,displayOrder:q.displayOrder,questionTextSnapshot:q.questionTextSnapshot,optionsSnapshot:q.optionsSnapshot,answer:q.answer||null}))});
function finalize(db, attemptId, mode='SUBMITTED'){ const a=db.attempts.find(x=>x.id===attemptId); if(!a) throw Error('Attempt not found'); if(a.status!=='IN_PROGRESS') return a; const season=db.seasons.find(s=>s.id===a.seasonId); let correct=0, wrong=0, unanswered=0, answered=0; for(const q of a.attemptQuestions){ if(!q.answer){unanswered++; continue;} answered++; if(q.answer.selectedOptionId === q.correctOptionSnapshot) correct++; else wrong++; } const total=a.attemptQuestions.length; const required=season.passingMethod === 'PERCENTAGE' ? Math.ceil(total * season.passingValue / 100) : season.passingValue; Object.assign(a,{status:mode,submittedAt:new Date().toISOString(),totalQuestions:total,answeredCount:answered,correctCount:correct,wrongCount:wrong,unansweredCount:unanswered,percentage: total ? Number((correct/total*100).toFixed(2)) : 0,result: correct >= required ? 'PASS':'FAIL'}); const p=db.progress.find(x=>x.userId===a.userId && x.seasonId===a.seasonId) || (db.progress.push({id:id('progress'),userId:a.userId,seasonId:a.seasonId,attemptCount:0}), db.progress.at(-1)); p.status=a.result==='PASS'?'PASSED':'FAILED'; p.bestScore=Math.max(p.bestScore||0, correct); p.bestPercentage=Math.max(p.bestPercentage||0, a.percentage); p.attemptCount=(p.attemptCount||0)+1; p.lastAttemptAt=a.submittedAt; if(a.result==='PASS') p.passedAt=a.submittedAt; db.notifications.push({id:id('notification'),userId:a.userId,title:`Season ${a.result}`,message:`Your score is ${correct}/${total} (${a.percentage}%).`,type:a.result,createdAt:new Date().toISOString()}); return a; }
const server = http.createServer(async (req,res)=>{ const db=readDb(); const url=new URL(req.url, `http://localhost:${PORT}`); try{
 if(req.method==='GET' && url.pathname==='/health') return send(res,200,{ok:true,url:`http://localhost:${PORT}`});
 if(req.method==='GET' && url.pathname==='/') return html(res, `<h1>Season-Based MCQ Examination Platform</h1><div class=card><p>Localhost app is running at <code>http://localhost:${PORT}</code>.</p><p>Login API seed users: <code>admin@example.com / Admin@12345</code> and <code>user@example.com / User@12345</code>.</p><a class=btn href=/seasons>Open seasons</a></div>`);
 if(req.method==='GET' && url.pathname==='/seasons'){ const seasons=db.seasons.filter(s=>s.status==='PUBLISHED').map(s=>`<div class=card><h2>${s.name}</h2><p>${s.description}</p><p>Questions: ${db.questions.filter(q=>q.seasonId===s.id).length} · Passing: ${s.passingValue}${s.passingMethod==='PERCENTAGE'?'%':' correct'}</p><code>POST /api/attempts {"seasonId":"${s.id}"}</code></div>`).join(''); return html(res, `<h1>Seasons</h1>${seasons}`); }
 if(req.method==='GET' && url.pathname==='/admin') return html(res, `<h1>Admin Panel</h1><div class=card><p>Use admin APIs after login. Publish validation, dynamic questions/options, audit logs, and dashboard metrics are implemented.</p><code>POST /api/auth/login</code><br><code>GET /api/admin/dashboard</code></div>`);
 if(req.method==='POST' && url.pathname==='/api/auth/login'){ const b=await parseBody(req); const u=db.users.find(x=>(x.email===b.login || x.email===b.email) && x.password===b.password); if(!u) return send(res,401,'Invalid credentials'); const sid=id('session'); db.sessions[sid]=u.id; if(u.role==='ADMIN') db.auditLogs.push({id:id('audit'),actorId:u.id,action:'ADMIN_LOGIN',targetEntity:'User',targetId:u.id,requestId:id('req'),createdAt:new Date().toISOString()}); writeDb(db); return send(res,200,{id:u.id,email:u.email,fullName:u.fullName,role:u.role},{'set-cookie':`session=${sid}; HttpOnly; Path=/; SameSite=Lax`}); }
 if(req.method==='POST' && url.pathname==='/api/auth/logout'){ delete db.sessions[cookieSession(req)]; writeDb(db); return send(res,200,{loggedOut:true},{'set-cookie':'session=; Max-Age=0; Path=/'}); }
 if(req.method==='GET' && url.pathname==='/api/auth/me') return send(res,200,userFromReq(req,db)||null);
 if(req.method==='GET' && url.pathname==='/api/user/seasons'){ const u=requireUser(req,res,db); if(!u) return; return send(res,200,db.seasons.filter(s=>s.status==='PUBLISHED').map(s=>({...s,questionCount:db.questions.filter(q=>q.seasonId===s.id).length, statusLabel:db.progress.find(p=>p.userId===u.id&&p.seasonId===s.id)?.status||'AVAILABLE'}))); }
 if(req.method==='GET' && url.pathname==='/api/user/dashboard'){ const u=requireUser(req,res,db); if(!u) return; const attempts=db.attempts.filter(a=>a.userId===u.id); return send(res,200,{availableSeasons:db.seasons.filter(s=>s.status==='PUBLISHED').length,totalAttempts:attempts.length,passed:attempts.filter(a=>a.result==='PASS').length,failed:attempts.filter(a=>a.result==='FAIL').length,averagePercentage:attempts.length?attempts.reduce((s,a)=>s+a.percentage,0)/attempts.length:0}); }
 if(req.method==='POST' && url.pathname==='/api/attempts'){ const u=requireUser(req,res,db); if(!u) return; const b=await parseBody(req); const season=db.seasons.find(s=>s.id===b.seasonId && s.status==='PUBLISHED'); if(!season) return send(res,404,'Season unavailable'); const questions=db.questions.filter(q=>q.seasonId===season.id).sort((a,b)=>a.displayOrder-b.displayOrder); const a={id:id('attempt'),userId:u.id,seasonId:season.id,status:'IN_PROGRESS',startedAt:new Date().toISOString(),deadlineAt:season.timerMinutes?new Date(Date.now()+season.timerMinutes*60000).toISOString():null,totalQuestions:questions.length,attemptQuestions:questions.map((q,i)=>({id:id('aq'),questionId:q.id,displayOrder:i+1,questionTextSnapshot:q.text,explanationSnapshot:q.explanation,marksSnapshot:q.marks,correctOptionSnapshot:q.options.find(o=>o.isCorrect).id,optionsSnapshot:q.options.map(o=>({id:o.id,text:o.text,displayOrder:o.displayOrder}))}))}; db.attempts.push(a); writeDb(db); return send(res,201,{attemptId:a.id}); }
 const attemptMatch=url.pathname.match(/^\/api\/attempts\/([^/]+)$/); if(req.method==='GET' && attemptMatch){ const u=requireUser(req,res,db); if(!u) return; const a=db.attempts.find(x=>x.id===attemptMatch[1] && x.userId===u.id); return a?send(res,200,publicAttempt(a)):send(res,404,'Attempt not found'); }
 const answerMatch=url.pathname.match(/^\/api\/attempts\/([^/]+)\/answers\/([^/]+)$/); if(req.method==='PUT' && answerMatch){ const u=requireUser(req,res,db); if(!u) return; const a=db.attempts.find(x=>x.id===answerMatch[1] && x.userId===u.id); if(!a) return send(res,404,'Attempt not found'); if(a.status!=='IN_PROGRESS') return send(res,409,'Attempt finalized'); if(a.deadlineAt && new Date()>new Date(a.deadlineAt)){ finalize(db,a.id,'AUTO_SUBMITTED'); writeDb(db); return send(res,409,'Timer expired; attempt auto-submitted'); } const q=a.attemptQuestions.find(x=>x.id===answerMatch[2]); const b=await parseBody(req); const opt=q?.optionsSnapshot.find(o=>o.id===b.selectedOptionId); if(!q || !opt) return send(res,400,'Invalid option'); q.answer={selectedOptionId:opt.id,selectedOptionTextSnapshot:opt.text,updatedAt:new Date().toISOString()}; writeDb(db); return send(res,200,{saved:true}); }
 const submitMatch=url.pathname.match(/^\/api\/attempts\/([^/]+)\/submit$/); if(req.method==='POST' && submitMatch){ const u=requireUser(req,res,db); if(!u) return; const a=db.attempts.find(x=>x.id===submitMatch[1] && x.userId===u.id); if(!a) return send(res,404,'Attempt not found'); const saved=finalize(db,a.id,a.deadlineAt&&new Date()>new Date(a.deadlineAt)?'AUTO_SUBMITTED':'SUBMITTED'); writeDb(db); return send(res,200,saved); }
 const resultMatch=url.pathname.match(/^\/api\/attempts\/([^/]+)\/result$/); if(req.method==='GET' && resultMatch){ const u=requireUser(req,res,db); if(!u) return; const a=db.attempts.find(x=>x.id===resultMatch[1] && x.userId===u.id); if(!a) return send(res,404,'Attempt not found'); if(a.status==='IN_PROGRESS') return send(res,409,'Attempt not submitted'); const season=db.seasons.find(s=>s.id===a.seasonId); const reqCorrect=season.passingMethod==='PERCENTAGE'?Math.ceil(a.totalQuestions*season.passingValue/100):season.passingValue; return send(res,200,{summary:{totalQuestions:a.totalQuestions,answered:a.answeredCount,unanswered:a.unansweredCount,correct:a.correctCount,wrong:a.wrongCount,score:`${a.correctCount}/${a.totalQuestions}`,percentage:a.percentage,passingRequirement:`${reqCorrect}/${a.totalQuestions}`,result:a.result,additionalCorrectNeeded:Math.max(0,reqCorrect-a.correctCount)},review:season.showAnswerReview?a.attemptQuestions.map(q=>({question:q.questionTextSnapshot,userAnswer:q.answer?.selectedOptionTextSnapshot||null,correctAnswer:q.optionsSnapshot.find(o=>o.id===q.correctOptionSnapshot).text,explanation:q.explanationSnapshot})):null}); }
 if(req.method==='GET' && url.pathname==='/api/admin/dashboard'){ if(!requireAdmin(req,res,db)) return; return send(res,200,{totalUsers:db.users.length,totalSeasons:db.seasons.length,publishedSeasons:db.seasons.filter(s=>s.status==='PUBLISHED').length,totalQuestions:db.questions.length,totalAttempts:db.attempts.length,passCount:db.attempts.filter(a=>a.result==='PASS').length,failCount:db.attempts.filter(a=>a.result==='FAIL').length}); }
 if(req.method==='POST' && url.pathname.match(/^\/api\/admin\/seasons\/[^/]+\/publish$/)){ const admin=requireAdmin(req,res,db); if(!admin) return; const seasonId=url.pathname.split('/')[4]; const errors=validateSeason(db,seasonId); if(errors.length) return send(res,422,`Season cannot be published. ${errors.join('; ')}`); db.seasons.find(s=>s.id===seasonId).status='PUBLISHED'; db.auditLogs.push({id:id('audit'),actorId:admin.id,action:'SEASON_PUBLISH',targetEntity:'Season',targetId:seasonId,requestId:id('req'),createdAt:new Date().toISOString()}); writeDb(db); return send(res,200,{published:true}); }
 if(req.method==='GET' && url.pathname==='/api/admin/audit-logs'){ if(!requireAdmin(req,res,db)) return; return send(res,200,db.auditLogs); }
 send(res,404,'Not found');
 }catch(e){ send(res,500, e.message || 'Server error'); }
});
server.on('error', (error) => {
  if (error.code === 'EADDRINUSE') {
    console.error(`Port ${PORT} is already in use. Open http://localhost:${PORT} if another SeasonExam server is already running, or run: PORT=4000 npm run dev`);
    process.exit(1);
  }
  console.error(error);
  process.exit(1);
});
server.listen(PORT, HOST, () => console.log(`SeasonExam local app: http://localhost:${PORT}`));
